// <auto-generated />
using System;
using BlazorPersonalWebsite.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorPersonalWebsite.EntityFramework.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    [Migration("20210506170657_addedImageRefs")]
    partial class addedImageRefs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BlazorPersonalWebsite.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobApplicationRef")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobApplication");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("ProjectRef");

                    b.ToTable("SoftwareProject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Skill action calculator for video game Runescape",
                            Name = "Runescape Calculator",
                            ProjectRef = "rsCalc"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2016, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "University e-commerce book store",
                            ProjectRef = "uniEcomm"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2016, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Loyalty Pro Android App",
                            ProjectRef = "loyaltyProApp"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "University Dissertation - GPS Logger",
                            ProjectRef = "uniDis"
                        });
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProjectImage", b =>
                {
                    b.Property<int>("SoftwareProjectImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftwareProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SoftwareProjectImageId");

                    b.HasIndex("SoftwareProjectId");

                    b.ToTable("SoftwareProjectImage");

                    b.HasData(
                        new
                        {
                            SoftwareProjectImageId = 1,
                            Description = "Agility skill calculator",
                            ImageUrl = "images\\software-images\\rs-calculator\\1.png",
                            SoftwareProjectId = 1
                        },
                        new
                        {
                            SoftwareProjectImageId = 2,
                            Description = "Fishing skill calculator",
                            ImageUrl = "images\\software-images\\rs-calculator\\2.png",
                            SoftwareProjectId = 1
                        },
                        new
                        {
                            SoftwareProjectImageId = 3,
                            Description = "Dropdown showing which skills are included",
                            ImageUrl = "images\\software-images\\rs-calculator\\3.png",
                            SoftwareProjectId = 1
                        },
                        new
                        {
                            SoftwareProjectImageId = 4,
                            Description = "Dropdown showing skill subcategories",
                            ImageUrl = "images\\software-images\\rs-calculator\\4.png",
                            SoftwareProjectId = 1
                        },
                        new
                        {
                            SoftwareProjectImageId = 5,
                            Description = "Ecommerce homepage",
                            ImageUrl = "images\\software-images\\ecommerce-site\\1.png",
                            SoftwareProjectId = 2
                        },
                        new
                        {
                            SoftwareProjectImageId = 6,
                            Description = "Ecommerce product page",
                            ImageUrl = "images\\software-images\\ecommerce-site\\2.png",
                            SoftwareProjectId = 2
                        },
                        new
                        {
                            SoftwareProjectImageId = 7,
                            Description = "Ecommerce basket page",
                            ImageUrl = "images\\software-images\\ecommerce-site\\3.png",
                            SoftwareProjectId = 2
                        },
                        new
                        {
                            SoftwareProjectImageId = 8,
                            Description = "Ecommerce admin page",
                            ImageUrl = "images\\software-images\\ecommerce-site\\4.png",
                            SoftwareProjectId = 2
                        },
                        new
                        {
                            SoftwareProjectImageId = 9,
                            Description = "Ecommerce admin page - Edit listing",
                            ImageUrl = "images\\software-images\\ecommerce-site\\5.png",
                            SoftwareProjectId = 2
                        },
                        new
                        {
                            SoftwareProjectImageId = 10,
                            Description = "Ecommerce contact us page",
                            ImageUrl = "images\\software-images\\ecommerce-site\\6.png",
                            SoftwareProjectId = 2
                        },
                        new
                        {
                            SoftwareProjectImageId = 11,
                            Description = "Main menu",
                            ImageUrl = "images\\software-images\\loyalty-pro-app\\1.png",
                            SoftwareProjectId = 3
                        },
                        new
                        {
                            SoftwareProjectImageId = 12,
                            Description = "Balance overview page",
                            ImageUrl = "images\\software-images\\loyalty-pro-app\\2.png",
                            SoftwareProjectId = 3
                        },
                        new
                        {
                            SoftwareProjectImageId = 13,
                            Description = "Personal details page",
                            ImageUrl = "images\\software-images\\loyalty-pro-app\\3.png",
                            SoftwareProjectId = 3
                        },
                        new
                        {
                            SoftwareProjectImageId = 14,
                            Description = "Vouchers overview page",
                            ImageUrl = "images\\software-images\\loyalty-pro-app\\4.png",
                            SoftwareProjectId = 3
                        },
                        new
                        {
                            SoftwareProjectImageId = 15,
                            Description = "Initial unlogged in page",
                            ImageUrl = "images\\software-images\\loyalty-pro-app\\5.png",
                            SoftwareProjectId = 3
                        },
                        new
                        {
                            SoftwareProjectImageId = 16,
                            Description = "Manual log in page",
                            ImageUrl = "images\\software-images\\loyalty-pro-app\\6.png",
                            SoftwareProjectId = 3
                        },
                        new
                        {
                            SoftwareProjectImageId = 17,
                            Description = "Display showing journeys between two staypoints",
                            ImageUrl = "images\\software-images\\gps-logger\\1.png",
                            SoftwareProjectId = 4
                        },
                        new
                        {
                            SoftwareProjectImageId = 18,
                            Description = "Individual journey view",
                            ImageUrl = "images\\software-images\\gps-logger\\2.png",
                            SoftwareProjectId = 4
                        },
                        new
                        {
                            SoftwareProjectImageId = 19,
                            Description = "Staypoint overview showing individual visits",
                            ImageUrl = "images\\software-images\\gps-logger\\3.png",
                            SoftwareProjectId = 4
                        },
                        new
                        {
                            SoftwareProjectImageId = 20,
                            Description = "Staypoint shown on map",
                            ImageUrl = "images\\software-images\\gps-logger\\4.png",
                            SoftwareProjectId = 4
                        },
                        new
                        {
                            SoftwareProjectImageId = 21,
                            Description = "Open side bar",
                            ImageUrl = "images\\software-images\\gps-logger\\5.png",
                            SoftwareProjectId = 4
                        });
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("ProjectRef");

                    b.ToTable("WoodworkProject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2017, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Side Gate",
                            ProjectRef = "sideGate"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2017, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workbench",
                            ProjectRef = "workbench"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2017, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bird table",
                            ProjectRef = "birdTable"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Raised Garden bed (Small)",
                            ProjectRef = "raisedGardenBendSmall"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Raised Garden bed (Large)",
                            ProjectRef = "raisedGardenBendLarge"
                        });
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProjectImage", b =>
                {
                    b.Property<int>("WoodworkProjectImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("WoodworkProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WoodworkProjectImageId");

                    b.HasIndex("WoodworkProjectId");

                    b.ToTable("WoodworkProjectImage");

                    b.HasData(
                        new
                        {
                            WoodworkProjectImageId = 1,
                            Description = "Unhung gate",
                            ImageRef = "unhungGate",
                            ImageUrl = "images\\woodwork-images\\side-gate\\sidegate-unhung.jpg",
                            WoodworkProjectId = 1
                        },
                        new
                        {
                            WoodworkProjectImageId = 2,
                            Description = "Unfinished workbench",
                            ImageRef = "unfinishedWorkbench",
                            ImageUrl = "images\\woodwork-images\\workbench\\workbench-unfinished.jpg",
                            WoodworkProjectId = 2
                        },
                        new
                        {
                            WoodworkProjectImageId = 3,
                            Description = "Bird Table",
                            ImageRef = "birdTable",
                            ImageUrl = "images\\woodwork-images\\bird-table\\bird-table.jpg",
                            WoodworkProjectId = 3
                        },
                        new
                        {
                            WoodworkProjectImageId = 4,
                            Description = "All raised garden beds",
                            ImageRef = "allRaisedBed",
                            ImageUrl = "images\\woodwork-images\\raised-garden-bed\\all-in-view.jpg",
                            WoodworkProjectId = 4
                        },
                        new
                        {
                            WoodworkProjectImageId = 5,
                            Description = "All raised garden beds",
                            ImageRef = "allRaisedBed2",
                            ImageUrl = "images\\woodwork-images\\raised-garden-bed\\all-in-view.jpg",
                            WoodworkProjectId = 5
                        });
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProjectImage", b =>
                {
                    b.HasOne("BlazorPersonalWebsite.Models.SoftwareProject", "SoftwareProject")
                        .WithMany("Images")
                        .HasForeignKey("SoftwareProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareProject");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProjectImage", b =>
                {
                    b.HasOne("BlazorPersonalWebsite.Models.WoodworkProject", "WoodworkProject")
                        .WithMany("Images")
                        .HasForeignKey("WoodworkProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WoodworkProject");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProject", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProject", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
